[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_USE_NETLIFY_EDGE = "true"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs"
  status = 200
